name       : xorgxrdp
version    : 0.2.16
release    : 4
source     :
    - https://github.com/neutrinolabs/xorgxrdp/releases/download/v0.2.16/xorgxrdp-0.2.16.tar.gz : e6b5f3df44cbf147dcbbc326cdd08c95fe28dba80c2a216e046fe42d962f9215
license    : X11
component  : xorg.driver
summary    : Xorg drivers for xrdp
description: |
    xorgxrdp is a collection of modules to be used with a pre-existing X.Org install to make the X server act like X11rdp.
builddeps  :
    - pkgconfig(xfont2)
    - pkgconfig(xorg-server)
    - pkgconfig(xrdp)
rundeps    :
    - xrdp
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
