name       : xorgxrdp
version    : 0.2.9
release    : 2
source     :
    - https://github.com/neutrinolabs/xorgxrdp/releases/download/v0.2.9/xorgxrdp-0.2.9.tar.gz : 2f24f468771c874d6cda86e09edcf5bd48e88894de9c4ebd2bef9cb6f255c688
license    : X11
component  : xorg.driver
summary    : Xorg drivers for xrdp
description: |
    xorgxrdp is a collection of modules to be used with a pre-existing X.Org install to make the X server act like X11rdp.
builddeps  :
    - pkgconfig(xfont2)
    - pkgconfig(xorg-server)
    - pkgconfig(xrdp)
rundeps    :
    - xrdp
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
